services:
  keycloak:
    container_name: keycloak-booking
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - 80:8080
      - 8443:8443
    volumes:
      - ./cert/keycloak.pem:/etc/x509/https/tls.crt
      - ./cert/keycloakKey.pem:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    networks:
      - spring-demo
    command:
      - "start-dev"

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local