package com.booking.project.model.enums;

public enum GuestPermission {
    CALENDAR_READ,
    ACCOMMODATION_READ,

    COMMENT_WRITE,
    COMMENT_READ,
    COMMENT_DELETE,

    FAVORITE_ACCOMMODATION_READ,
    FAVORITE_ACCOMMODATION_WRITE,
    FAVORITE_ACCOMMODATION_DELETE,
    FAVORITE_READ,

    NOTIFICATION_READ,
    NOTIFICATION_UPDATE,
    NOTIFICATION_STATUS_READ,
    NOTIFICATION_STATUS_UPDATE,

    RESERVATION_READ,
    RESERVATION_WRITE,
    RESERVATION_PRICE_READ,
    RESERVATION_PENDING_DELETE,
    RESERVATION_ACCEPT_DELETE,

    USER_DELETE,
    USER_UPDATE,
    USER_STATUS_UPDATE,
    REPORT_USER_WRITE
}
