package com.booking.project.model.enums;

public enum HostPermission {
    ACCOMMODATION_WRITE,
    ACCOMMODATION_DELETE,
    ACCOMMODATION_READ,
    ACCOMMODATION_UPDATE,

    RESERVATION_UPDATE,

    ACCOMMODATION_PRICE_LIST_WRITE,
    ACCOMMODATION_PRICE_LIST_UPDATE,
    ACCOMMODATION_PRICE_LIST_READ,

    ANALYTICS_READ,

    COMMENT_REPORT_WRITE,

    REPORT_MESSAGE_UPDATE,

    NOTIFICATION_READ,
    NOTIFICATION_UPDATE,
    NOTIFICATION_STATUS_READ,
    NOTIFICATION_STATUS_UPDATE,

    RESERVATION_READ,
    RESERVATION_STATUS_UPDATE,

    USER_DELETE,
    USER_UPDATE,
    USER_STATUS_UPDATE,
    REPORT_USER_WRITE
}
